### ISSUE TITLE
cri为containerd时,额外安装cni不可用

### ISSUE THREAD

**Issue by blue-troy** [KubeOperator/ansible#4]
cni bin_dir 默认目录为 /opt/cni/bin,额外安装的cni会安装到这个目录下.但是目前containerd
config配置

[代码](https://github.com/blue-troy/ansible/blob/master/roles/prepare/containerd/templates/config.toml.j2#L49)

```bash
    [plugins.cri.cni]
      bin_dir = "{{ bin_dir }}"
      conf_dir = "/etc/cni/net.d"
      conf_template = ""
```

cni bin_dir为{{ bin_dir
}},它的值为/usr/local/bin,不符合cni标准.kubeoperator在安装cni如flannel时将flannel
bin同时放在了 /usr/local/bin 以及
/opt/cni/bin,因此cni配置为/usr/local/bin没有问题,但是一旦安装其他第三方cni则将出现问题

**Comment by blue-troy** [comment]
在运行时为docker时 kubeoperator将cni bin path设为/opt/cni/bin 而containerd时却在containerd的配置中加入配置cni bin path为/usr/local/bin.

**Comment by wanghe-fit2cloud** [comment]
已修复
