### ISSUE TITLE
重启后kubelet无法启动

### ISSUE THREAD

**Issue by blue-troy** [KubeOperator/ansible#6]
由于swap未关闭导致的kubelet 无法启动问题。

在安装k8s时,playbook使用 [swapoff -a](https://github.com/KubeOperator/ansible/blob/master/roles/prepare/base/tasks/common.yml#L2) 保证了swap处于关闭状态。后续机器重启，swap未处于关闭状态，因此kubelet无法启动。

我看到项目playbook使用了[去除/etc/fstab的办法](https://github.com/KubeOperator/ansible/blob/master/roles/prepare/base/tasks/common.yml#L5)。但是并不是所有swap都是用fstab进行维护。

1. 根据 [archlinux](https://wiki.archlinux.org/title/Systemd#GPT_partition_automounting) 中提到的，可以利用GPT自动挂载实现不是使用fstab实现自动swap挂载，这个办法是自动扫描分区的类型，删除fstab无法处理这种的问题。
2. systemd-fstab-generator读取fstab生成包括swap的units，但这不意味着所有的swap unit都是由systemd-fstab-generator生成，我们可以自定义swap unit 实现swap挂载。

以上问题是具体环境中使用遇到的问题。

**Comment by wanghe-fit2cloud** [comment]
Get.
